SCRFD:
  onnx_file: "resources/Face/scrfd_500m_320_1.onnx"
  engine_file: "resources/Face/scrfd_500m_320_1.engine"
  BATCH_SIZE: 1
  IMAGE_WIDTH: 320
  IMAGE_HEIGHT: 320
  INPUT_CHANNEL: 3
  obj_threshold: 0.6
  nms_threshold: 0.45
